### ISSUE TITLE
Create SQLite Database with all necessary tables

### ISSUE THREAD

**Issue by ApolloFortyNine** [Benderx/leaguestats#1]

**Comment by Benderx** [comment]
ayy

**Comment by Benderx** [comment]
whats sql

**Comment by Benderx** [comment]
whats sql

**Comment by ApolloFortyNine** [comment]
May need to create new tables for each field in ParticipantTimeline. Or figure out how custom datatypes work.

**Comment by ApolloFortyNine** [comment]
Use tables for each field, just copy paste one and rename.
