### ISSUE TITLE
Write functions, in a class, to return an array of each level of JSON objects. i.e: an array of Event JSON Objects by minute, an array of player location by minute, an array of runes by player, an array of masteries by palyers.

### ISSUE THREAD

**Issue by aduerig** [Benderx/leaguestats#2]

**Comment by ApolloFortyNine** [comment]
Your going to have to loop through the JSON object and store in a new JSON object only what you need. So when looping through just do newDict['key'] = oldDict['key']

**Comment by ApolloFortyNine** [comment]
You can create an array of strings that are the keys you want, then do "if (x in array): dostuff"

**Comment by ApolloFortyNine** [comment]
https://developer.riotgames.com/api/methods#!/967/3313

Return JSON objects of each category containing everything but the lists.

**Comment by ApolloFortyNine** [comment]
When creating the JSON's, if there is something nested along with the data create a dictionary with model {'flat':FLATDICT, 'nameOfNest':NESTDICT}

**Comment by aduerig** [comment]
I ran into a problem when attempting to implement the first nested dictionary, Participant. I am unsure how to nest it, since in this case there will have to be 10 nests total. For example, I could set up the nest like this {'flat':MATCHDETAILDICT, 'Particpant1':NESTDICT1, 'Particpant2':NESTDICT2..., 'Particpant10':NESTDICT10}
or is there another way you want me to do this?

**Comment by ApolloFortyNine** [comment]
Participants should be an array of dictionaries. So all those you typed out should be in 'participant' : [dict, dict2].  You may want to use recursion here, or make it so your functions only pass on the part they are working on (so only send participant frames and nothing above it to the participant frames function). 

In reality how the json is set up is already almost good enough, I'd just like to have only parts be returned at a time.
